"""add incremental graph reasoning schema

Revision ID: cbfd1a878428
Revises: 0027_add_chunk_cancelled_status
Create Date: 2026-07-13 06:51:01.833218
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "cbfd1a878428"
down_revision = "0027_add_chunk_cancelled_status"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graph_chunk_segments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("document_path", sa.String(length=1024), nullable=True),
        sa.Column("chunk_hash", sa.String(length=64), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("contract_version", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("raw_extraction", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tombstoned_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["collections.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "collection_id",
            "chunk_hash",
            "contract_version",
            name="uq_graph_chunk_segment_contract",
        ),
    )
    op.create_index(
        op.f("ix_graph_chunk_segments_collection_id"),
        "graph_chunk_segments",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_chunk_segments_document_id"),
        "graph_chunk_segments",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        "ix_graph_chunk_segments_document_order",
        "graph_chunk_segments",
        ["collection_id", "document_id", "chunk_index"],
        unique=False,
    )
    op.create_table(
        "graph_derived_dependencies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("target_kind", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("dependency_type", sa.String(length=32), nullable=False),
        sa.Column("overlay_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["collections.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "collection_id",
            "source_kind",
            "source_id",
            "target_kind",
            "target_id",
            "dependency_type",
            "overlay_version",
            name="uq_graph_derived_dependency",
        ),
    )
    op.create_index(
        op.f("ix_graph_derived_dependencies_collection_id"),
        "graph_derived_dependencies",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        "ix_graph_derived_dependencies_target",
        "graph_derived_dependencies",
        ["collection_id", "target_kind", "target_id"],
        unique=False,
    )
    op.create_table(
        "graph_chunk_contributions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("segment_id", sa.UUID(), nullable=False),
        sa.Column("object_kind", sa.String(length=32), nullable=False),
        sa.Column("object_id", sa.UUID(), nullable=False),
        sa.Column("contribution_kind", sa.String(length=32), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["collections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"], ["graph_chunk_segments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "segment_id",
            "object_kind",
            "object_id",
            "contribution_kind",
            name="uq_graph_chunk_contribution_object",
        ),
    )
    op.create_index(
        op.f("ix_graph_chunk_contributions_collection_id"),
        "graph_chunk_contributions",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        "ix_graph_chunk_contributions_reverse",
        "graph_chunk_contributions",
        ["collection_id", "object_kind", "object_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_chunk_contributions_segment_id"),
        "graph_chunk_contributions",
        ["segment_id"],
        unique=False,
    )
    op.create_table(
        "graph_entity_mappings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("segment_id", sa.UUID(), nullable=False),
        sa.Column("local_key", sa.String(length=256), nullable=False),
        sa.Column("raw_name", sa.String(length=256), nullable=False),
        sa.Column("raw_type", sa.String(length=64), nullable=True),
        sa.Column("canonical_entity_id", sa.UUID(), nullable=False),
        sa.Column("resolution_method", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("mapping_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_entity_id"], ["graph_entities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["collections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"], ["graph_chunk_segments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "segment_id", "local_key", name="uq_graph_entity_mapping_local"
        ),
    )
    op.create_index(
        op.f("ix_graph_entity_mappings_canonical_entity_id"),
        "graph_entity_mappings",
        ["canonical_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_entity_mappings_collection_id"),
        "graph_entity_mappings",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_entity_mappings_segment_id"),
        "graph_entity_mappings",
        ["segment_id"],
        unique=False,
    )
    op.create_table(
        "graph_entity_redirects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("source_entity_id", sa.UUID(), nullable=False),
        sa.Column("target_entity_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.String(length=128), nullable=True),
        sa.Column("mapping_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["collections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_entity_id"], ["graph_entities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_entity_id"], ["graph_entities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_entity_id"),
    )
    op.create_index(
        op.f("ix_graph_entity_redirects_collection_id"),
        "graph_entity_redirects",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_entity_redirects_target_entity_id"),
        "graph_entity_redirects",
        ["target_entity_id"],
        unique=False,
    )
    op.create_table(
        "graph_predicate_mappings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("segment_id", sa.UUID(), nullable=False),
        sa.Column("raw_predicate", sa.String(length=128), nullable=False),
        sa.Column("canonical_predicate_id", sa.UUID(), nullable=False),
        sa.Column("resolution_method", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("mapping_version", sa.Integer(), nullable=False),
        sa.Column("inferred_properties", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["canonical_predicate_id"],
            ["graph_relationship_types.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["collections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"], ["graph_chunk_segments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "segment_id", "raw_predicate", name="uq_graph_predicate_mapping_local"
        ),
    )
    op.create_index(
        op.f("ix_graph_predicate_mappings_canonical_predicate_id"),
        "graph_predicate_mappings",
        ["canonical_predicate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_predicate_mappings_collection_id"),
        "graph_predicate_mappings",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_predicate_mappings_segment_id"),
        "graph_predicate_mappings",
        ["segment_id"],
        unique=False,
    )
    op.create_table(
        "graph_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parent_version_id", sa.UUID(), nullable=True),
        sa.Column("delta_segment_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["collections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["delta_segment_id"], ["graph_chunk_segments.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["parent_version_id"], ["graph_versions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "collection_id", "version", name="uq_graph_version_collection"
        ),
    )
    op.create_index(
        op.f("ix_graph_versions_collection_id"),
        "graph_versions",
        ["collection_id"],
        unique=False,
    )
    op.create_table(
        "graph_projection_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("graph_version_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("spec_hash", sa.String(length=64), nullable=False),
        sa.Column("specification", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("node_count", sa.Integer(), nullable=False),
        sa.Column("edge_count", sa.Integer(), nullable=False),
        sa.Column("diagnostics", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["graph_version_id"], ["graph_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "graph_version_id",
            "name",
            "spec_hash",
            name="uq_graph_projection_snapshot_spec",
        ),
    )
    op.create_index(
        op.f("ix_graph_projection_snapshots_graph_version_id"),
        "graph_projection_snapshots",
        ["graph_version_id"],
        unique=False,
    )
    op.create_table(
        "graph_communities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("projection_id", sa.UUID(), nullable=False),
        sa.Column("algorithm", sa.String(length=64), nullable=False),
        sa.Column("community_key", sa.String(length=128), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["projection_id"], ["graph_projection_snapshots.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "projection_id", "algorithm", "community_key", name="uq_graph_community_key"
        ),
    )
    op.create_index(
        op.f("ix_graph_communities_projection_id"),
        "graph_communities",
        ["projection_id"],
        unique=False,
    )
    op.create_table(
        "graph_component_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("projection_id", sa.UUID(), nullable=False),
        sa.Column("component_key", sa.String(length=128), nullable=False),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["projection_id"], ["graph_projection_snapshots.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "projection_id", "component_key", "metric", name="uq_graph_component_metric"
        ),
    )
    op.create_index(
        op.f("ix_graph_component_metrics_projection_id"),
        "graph_component_metrics",
        ["projection_id"],
        unique=False,
    )
    op.create_table(
        "graph_node_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("projection_id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["graph_entities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["projection_id"], ["graph_projection_snapshots.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "projection_id", "entity_id", "metric", name="uq_graph_node_metric"
        ),
    )
    op.create_index(
        op.f("ix_graph_node_metrics_entity_id"),
        "graph_node_metrics",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_node_metrics_projection_id"),
        "graph_node_metrics",
        ["projection_id"],
        unique=False,
    )
    op.create_table(
        "graph_community_memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("community_id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("strength", sa.Float(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["community_id"], ["graph_communities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["graph_entities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "community_id", "entity_id", name="uq_graph_community_membership"
        ),
    )
    op.create_index(
        op.f("ix_graph_community_memberships_community_id"),
        "graph_community_memberships",
        ["community_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_community_memberships_entity_id"),
        "graph_community_memberships",
        ["entity_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_table("graph_community_memberships")
    op.drop_table("graph_node_metrics")
    op.drop_table("graph_component_metrics")
    op.drop_table("graph_communities")
    op.drop_table("graph_projection_snapshots")
    op.drop_table("graph_versions")
    op.drop_table("graph_predicate_mappings")
    op.drop_table("graph_entity_redirects")
    op.drop_table("graph_entity_mappings")
    op.drop_table("graph_chunk_contributions")
    op.drop_table("graph_derived_dependencies")
    op.drop_table("graph_chunk_segments")
